title: c13u
description: Chege Gitau's personal site
url: https://www.c13u.com/
author: Chege Gitau
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-redirect-from
  - jekyll-feed
collections:
  people_affairs:
    output: true
  personal_growth:
    output: true
  business:
    output: true
  technology:
    output: true
collections_dir: notebooks